[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.139.0"
  HUGO_ENV = "production"

[context.production]
  command = "hugo --gc --minify"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture --buildDrafts"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

