apiVersion: v2
name: portfolio
description: A Helm chart for deploying Munish Thakur's portfolio website
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: Munish Thakur
    email: thakurmunish2806@gmail.com
    url: https://methakur.info

keywords:
  - portfolio
  - hugo
  - static-site
  - nginx

home: https://github.com/menotthakur/portfolio
sources:
  - https://github.com/menotthakur/portfolio

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/menotthakur/portfolio
    - name: Website
      url: https://methakur.info

